### PR TITLE
remove ctl builds and build everything using local tooling

### PR DESCRIPTION
**Pull request by tgunnoe**
related to: 
https://github.com/input-output-hk/partner-chains-smart-contracts/compare/master...pc-redo-nix
### Prereview checklist

- [ ] The [CHANGELOG.md](../blob/master/CHANGELOG.md) has been updated under the `# Unreleased` header using the appropriate sub-headings with links to the appropriate issues/PRs.
- [x] All tests pass in CI
- [x] PR was self-reviewed

### CODE REVIEW

**Comment by gilligan** [comment]
@tgunnoe 

```
error: attribute 'bundlePursProjectEsbuild' missing
```

**Comment by gilligan** [comment]
@jankun4 @kpinter-iohk could you please give this branch a try to check your usual workflows?

**Comment by kpinter-iohk** [comment]
When I check out this branch and I run
* `nix develop`
* `cd offchain`
* `make clean`
* `make build`
I get many errors from spago like:
```
[error] 
Failed to install dependency "aff-retry"
Git output:

fatal: destination path '.' already exists and is not an empty directory.


Aborting installation..
```

**Comment by tgunnoe** [comment]
@kpinter-iohk 
thanks, i'm looking into it.  I see this with `spago build`

but when I have a fresh clone of `master` and do those steps, i get this:
```
$ make build
Generating `src/TrustlessSidechain/RawScripts.purs` with the following command...
Warning: Both /home/tgunnoe/.cabal and /home/tgunnoe/.config/cabal/config
exist - ignoring the former.
It is advisable to remove one of them. In that case, we will use the remaining
one by default (unless '$CABAL_DIR' is explicitly set).
Warning: The package list for 'hackage.haskell.org' is 114 days old.
Run 'cabal update' to get the latest list of available packages.
Error: [Cabal-7159]
Latest known index-state for 'hackage.haskell.org' (2024-05-06T16:48:53Z) is older than the requested index-state (2024-07-16T05:49:34Z).
Run 'cabal update' or set the index-state to a value at or before 2024-05-06T16:48:53Z.

make: *** [Makefile:63: src/TrustlessSidechain/RawScripts.purs] Error 1
```
and I get the same thing on this branch.

let me look a bit more

**Comment by tgunnoe** [comment]
As per your error:
It's something to do with the version of spago that's in nixpkgs vs the one from the purescript overlays. That's really annoying, because they print the same version. Unfortunately the overlay is binaries only and doesn't have aarch64-darwin (macos natives). so I'm going to have to introspect to why they are different. =\

**Comment by tgunnoe** [comment]
@kpinter-iohk could you try the latest commit, which uses, from what i can tell, the good working version of `spago 0.21.0`, and see if anything else is non-functional ?

This is going to fail on macOS of course, but i'm looking into the differences

**Review by kpinter-iohk — APPROVED** [review]
Tested after the fix, everything seems to be working well!

**Pull request merged**
